import Head from 'next/head'
import Link from 'next/link';
import { Container, Typography } from '@mui/material';
import { ReactElement } from 'react';
import Layout from './layout';
import SliderSection from './sections/SliderSection/SliderSection';
import CatalogSection from './sections/CatalogSection/CatalogSection';
import { loadErrorMessages, loadDevMessages } from "@apollo/client/dev";

loadDevMessages();
loadErrorMessages();
export default function Home() {
    return (
        <>
            <Head>
                <title>Host App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <SliderSection />
            <CatalogSection />
            <Container>
                <Typography variant="h1">Hello world</Typography>
                <Link href="/admin">to admin</Link>
            </Container>
        </>
    )
}

Home.getLayout = function (page: ReactElement) {
    return <Layout>{page}</Layout>
}